### ISSUE TITLE
Unable to understand lib.js

### ISSUE THREAD

**Issue by senthil-bungee** [studiogangster/realtime-option-algo-trader#1]
Hello,

I try to debug code of lib.js. It looks like code copied from sensibull site. The code was minified and hence we see unreadable code. 
1. How did you locate this file from main.js?
2. Is it possible to provide meaniful name for that code?
3. The code is not downloading option chain. I followed the steps in readme.

**Comment by studiogangster** [comment]
1. Reverse engineering sensibull's source-code & APIs.
2. Can be planned at a later stage.
3. Modified the 'README' and updated the instructions. Simply use docker to run the project.

**Comment by senthil-bungee** [comment]
How did you exactly pick those scripts? What was the procedure to pull them? Do you some documentation of it?

**Comment by studiogangster** [comment]
Readable lib.js code updated at: 
https://github.com/studiogangster/realtime-option-algo-trader/blob/main/realtime-data/lib-deobfuscated.js

How it was done...remains out-of-scope from this discussion !
